### ISSUE TITLE
The board is using the wrong colours.

### ISSUE THREAD

**Issue by edupont** [LinusCDE/chessmarkable#3]
On usual chess boards, the lower-left tile is black.

I think you can fix it by negating this condition in game_scene.rs:256
`let is_bright_bg = x % 2 == y % 2;`

**Comment by LinusCDE** [comment]
Thanks. I looked at at when creating it, but somehow it slipped me. The color codes/gray values were wrong for that condition.

**Comment by LinusCDE** [comment]
Since it will probably take at least a day for a new release on toltec and I want to fix issue #2 also for the next version, [here](https://transfer.cosmos-ink.net/7Q71G/chessmarkable) is the binary with the adjusted pattern (should be able to just replace the current one in `/opt/bin/` or run manually).

**Comment by edupont** [comment]
Thanks for the quick fix!

You may want to update the screenshots on the README.md file as well.

**Comment by LinusCDE** [comment]
Will do that after #4 is sorted out.
