### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by Rafail-P** [LinusCDE/chessmarkable#7]
Hi!
I'm new to linux, less than a beginner.
I tried to install chessmarkable according to the instructions from .md, but these instructions are too brief for my level.
I would need some clarification:
I downloaded the chessmarkable file the one without any extension but I didn't know where to copy it. (I copied it in both home / root and usr / lib). Where exactly should it be placed?
Further in the .md file you mention something about compiling with "cargo build --release ...". Can it be more detailed? Is this a linux command or a Qtcreator menu?
I managed to install Qtcreator and toolchain from reMarkable and I tried to compile the code provided by ddvk / remarkable2-framebuffer, I got a file librm2fb_client.so.1.0.0 which I didn't know where to copy. I put it in usr / lib and I added the line "Environment = / usr / lib / librm2fb_client.so.1.0.0 in xochitl.service"
When I start the chess app with ./chessmarkable the remarkable device detects my touches, but does not display the chessboard. I get something like that in the Linux terminal:
![Captură de ecran din 2020-12-02 21-17-45](https://user-images.githubusercontent.com/73402820/100923342-b5602980-34e7-11eb-923a-15c48a839d50.png)
Please help if it is not too much...

**Comment by LinusCDE** [comment]
Hi,

> I downloaded the chessmarkable file the one without any extension but I didn't know where to copy it. (I copied it in both home / root and usr / lib). Where exactly should it be placed?

the "chessmarkable" file is basically like an exe on windows and "./<NAME>" is a double click. The location doesn't matter

> Further in the .md file you mention something about compiling with "cargo build --release ...". Can it be more detailed? Is this a linux command or a Qtcreator menu?

The program doesn't have anything to do with QT aside that the recommended toolchain also provides QT tooling. The remarkable2-framebuffer uses qmake, but i thinks that is more habit than requirement. The [remarkable2-framebuffer](https://github.com/ddvk/remarkable2-framebuffer/) repo is still very much in development. So instructions and user friendlness are not a priority at the moment, yet.

You can compile the program yourself, but this is mainly targeted at developers as you need to setup rust nightly and some cross-compiler toolchain like [oecore](https://remarkable.engineering/oecore-x86_64-cortexa9hf-neon-toolchain-zero-gravitas-1.8-23.9.2019.sh).

### Instructions for the shim

I don't own a rM2 myself, so I can only hope that my instructions will work. No guarantees.

- I compiled the project like documented in the README: [remarkable2-framebuffer.tar.gz](https://github.com/LinusCDE/chessmarkable/files/5631872/remarkable2-framebuffer.tar.gz)
- Xochitl should probably be stopped (that is the default ui, it'll reappar on reboot or when starting it again): `$ systemctl stop xochitl`
- Take the files `src/client/librm2fb_client.so.1.0.0` and `src/server/librm2fb_server.so.1.0.0` (e.g. from the above compiled tar.gz) and put it somewhere (e.g. in /home/root).
- Run this command: `$ LD_PRELOAD=librm2fb_server.so.1.0.0 /usr/bin/remarkable-shutdown`
- Open a second shell and run `$ LD_PRELOAD=librm2fb_client.so.1.0.0 ./chessmarkable`
- It should work now
- Once done, either exit from UI or press CTRL+C
- Stop the server in the other shell
- Start xochitl again with `$ systemctl start xochitl`

### Touch still not right

If the app displays, you'll probably notice that the touch doesn't register where you press it. I assumed a wrong rotation of the touch layer when [adding rM2 input support](https://github.com/canselcik/libremarkable/pull/48) to libremarkable. Most disussions regarding touch input and other support for rust based apps is here: https://github.com/canselcik/libremarkable/issues/46

I you get chessmarkable to run with the shim (aka. the remarkable2-framebuffer client.so), it would be nice, if you could check whether a alternative rotation works. Just try these files instead of chessmarkable and check which one works:
[other_touch_rotations.tar.gz](https://github.com/LinusCDE/chessmarkable/files/5631916/other_touch_rotations.tar.gz)

**Comment by LinusCDE** [comment]
Could this solve your problems?

Also the newest release should now fully support the inputs. The previous one was mis-mapped (i.e. buttons were not clickable where they were on the screen).

**Comment by mig2000** [comment]
I am also new to Linux and trying to install this on my RM2. Is there a simple instructions I can follow? If so, please advise. 

Thanks

**Comment by LinusCDE** [comment]
Hi. The easiest is to install it with toltec and use a launcher to start it. The current launchers seem to now utilize the shim automatically on the rM 2.

Head over to https://toltec-dev/toltec , use the three liner and add a launcher (oxide or remux). The stable release of retris and chessmarkable will have wrong input mapping until probably the next week or so. Either switch to the testing branch by editing `/opt/etc/opkg.conf` (on your own risk of course) or download the .ipk file from the latest release here, transfer it to the rm and `opkg install path/to/package.ipk` it. It should automatically appear in your launcher (maybe reload or restart it if it doesn't) and launch properly from there.

**Comment by MRUnbekanntOP** [comment]
Hi, I have a similar Problem: The startup of chessmarkable works fine, and i also see in the ssh logs that my inputs on the touch screen are correctly processed. my only problem is that i  don't get a screen update, and the screen only shows the picture of the point when i stopped xochitl.

**Comment by MRUnbekanntOP** [comment]
I alerady tested LinusCDE's solution, but it didn't work.

**Comment by LinusCDE** [comment]
Do other homebrew apps work? Maybe remarkable-framebuffer (display in opkg) isn't install properly or not running.

**Comment by MRUnbekanntOP** [comment]
I tested it with other apps like the calculator, which didn‘t work. rm2fb is not the problem, I reinstalled it multiple times and the console of chessmarkable also showed that it recognized rm2fb because there wasn‘t the warning that it didn‘t run

**Comment by LinusCDE** [comment]
> I tested it with other apps like the calculator, which didn‘t work. rm2fb is not the problem

If other apps don't work, it would most likely be a problem with rm2fb imo. The latest version of chessmarkable doesn't yet use the integrated swtfb (rm2fb) integration. It only checks if the env is correct to point out a configuration error.

If it doesn't see that, it'll treat the rM 2 Framebuffer like it was a rM 1 and assume, that rm2fb will automatically meddle with it and translate rM 1 FB operations for the rM 2. If rm2fb for some reason cannot start, it'll just send the operations to the rM 2 FB which will do nothing of value with it. So the chessmarkable will not be able to detect that anything is wrong, but you'll get no updates on the E-Ink.

A common issue with rm2fb is, that it doesn't have the function addresses for your specific firmware version due to being outdated or the new firmware not having gotten support yet. [This issue](https://github.com/ddvk/remarkable2-framebuffer/issues/18) tracks all the new addresses for new firmware which usually result in PRs adding the content posted in comments there.

If your firmware was not added when you downloaded rm2fb you either need to update it (if it was already merged) or alternatively grab the snippet for your firmware, paste it in one of [these config files](https://github.com/ddvk/remarkable2-framebuffer/blob/5f20bd6272ee5190ee499f58dcf6d7ea8a76548c/README.md#configuration) and reboot the device.

The rM 2 is pretty messy in regards to getting the framebuffer to work, but thankfully the people behind [remarkable2-framebuffer](https://github.com/ddvk/remarkable2-framebuffer/) did an amazing job of getting it to work in a compatible way with basically all homebrew apps. It's usually either all homebrew apps work or none do.

**Comment by MRUnbekanntOP** [comment]
Thanks for the tips. By manually adding the offsets, i was able to start the chess program. it worked fine, but after i pressed the exit-button, the device crashed. Since then, it is stuck in a boot loop ("reMarkable is starting" --> blank screen -->"reMarkable is restarting" --> blank screen --> "reMarkable is starting"). I already tried to use ssh, but neither the normal address  nor the "10.11.99.1"-address worked. I also tried ssh over USB, but this also didn't work. I have the ssh password noted if i find a way to get back on the device.

**Comment by MRUnbekanntOP** [comment]
It could be a problem with rm2fb, but i already searched for solution on the rm2fb-github, but all similar issues have an ssh connection active. So, none of these were able to help me. Also, I don't want to do a Factory reset because of the ssh password.

**Comment by rmadhwal** [comment]
I ran into a similar issue after doing a toltec update on an unsupported firmware version, if I had to guess you somehow messed up your system's binaries while trying to get rm2fb working and it is now having issues booting up (thus the ssh process doesn't even start).

You can recover your RM2 by following the instructions at [dvdk's remarkable recovery](https://github.com/ddvk/remarkable2-recovery), there is also a remarkable discord server where you could get help on the recovery process.
