### ISSUE TITLE
Over the board orientation for black pieces 

### ISSUE THREAD

**Issue by tomginsberg** [LinusCDE/chessmarkable#8]
Hi, this is a great remarkable app. The setup was also super painless. 

My only complaint is that in over the board (player v player) mode the black pieces don't switch orientation this makes it a bit disorienting for the player playing black. Would be a nice option if the pieces could flip or if you could toggle black/ white on the bottom so you could simply pass the tablet around.

**Comment by LinusCDE** [comment]
Hi,
that's a good idea. The easiest would probably be to flip all pieces when black has the turn. I initially didn't do it, since I wanted to keep screen refreshments to a minimum, but it should work out. I'll probably have to do some caching, since in the current state, I would need to composite the figures with the background again which taxes the cpu.

I'll see to get it done in the next few days.

**Comment by LinusCDE** [comment]
I added the feature now. It's currently not the most efficient but feels fluid.

I just rotate all pieces when it's blacks turn. Whether to enable this can be selected in the main menu.

More in this release: https://github.com/LinusCDE/chessmarkable/releases/tag/0.6.0-1

A screenshot of the main menu is also in the readme. If you have any further suggestions, please let me know. I may do some performance fixed in the next weeks anyway (hopefully).

**Comment by Eeems** [comment]
Another option you could use is to keep the black pieces always flipped? Probably not as ideal, but I could get use to that one.

**Comment by tomginsberg** [comment]
Thanks for the update

**Comment by LinusCDE** [comment]
> Another option you could use is to keep the black pieces always flipped? Probably not as ideal, but I could get use to that one.

Thought of this first as well. I also think this would be less then ideal since one would see the enemy always flipped. Even if one could get used to it, it would be weird for any new person. Maybe there are better images for a symmetric view in that case.

> Thanks for the update

No problem. If there any thinks to adjust, let me know. :smile:
